---
title: "Presidential Election Poll 1987"
author: "coop711"
date: "2015년 5월 5일"
output: html_document
---

Data Read-in
------------

`table` 구조를 가지므로 우선 `matrix`로 읽어들인다.

```{r}
poll.87<-matrix(c(289, 84, 26, 361, 154, 139, 53, 292, 126, 145, 57, 287, 61, 29, 11, 80), nrow=4, ncol=4)
poll.87
class(poll.87)
str(poll.87)
```

`table` 구조의 변수명을 정한다.

```{r}
dimnames(poll.87)<-list(c("Buddhism","Protestant","Catholic","None"),c("Roh","YS","DJ","JP"))
poll.87
```

`table` 구조로 강제 변환.

```{r}
poll.87.tbl<-as.table(poll.87)
str(poll.87.tbl)
```

`table` (실상은 `matrix`) 구조를 가지므로 `barplot()` 으로 막대들을 쌓아놓기 적합.

```{r fig.width=7, fig.height=7}
barplot(poll.87.tbl)
```

범례가 필요하다면 `rownames()`가 설정되어 있으므로 `legend.text=TRUE`로 충분함. 적절한 주제목 설정.

```{r fig.width=7, fig.height=7}
barplot(poll.87.tbl, legend.text=TRUE)
title(main="Poll 1987")
```

종교를 색깔로 구분하면,

```{r fig.width=7, fig.height=7}
barplot(poll.87.tbl, legend.text=TRUE, col=rainbow(4))
title(main="Poll 1987")
```


이를 `mosiacplot()`으로 비교해 보려면 `t()`작업을 취해야 제대로 볼 수 있음.

```{r fig.width=7, fig.height=7}
mosaicplot(t(poll.87.tbl), main="Poll 1987")
```

변수명이 겹치지 않도록 `las=1`를 적용하면,

```{r fig.width=7, fig.height=7}
mosaicplot(t(poll.87.tbl), las=1, main="Poll 1987")
```

종교별로 색깔을 씌우면,

```{r fig.width=7, fig.height=7}
mosaicplot(t(poll.87.tbl), las=1, main="Poll 1987", color=rainbow(4))
```

카이제곱 적합도 검정
--------------------

실제 득표율은 다음 표와 같음.

```{r}
result.87<-c(36.6, 28.0, 27.1, 8.1)
names(result.87)<-dimnames(poll.87.tbl)[[2]]
paste(result.87, "%", sep="")
```

poll sample은 result.87으로부터의 simple random sample로 볼 수 있는가?
우선, 후보별 예상지지율을 계산하기 위하여 표본지지자수를 합산해 보면,

```{r}
apply(poll.87.tbl, 2, sum)
```

여기에 카이제곱 검정을 적용해 보면,

```{r}
chisq.test(apply(poll.87.tbl, 2, sum), p=result.87/sum(result.87))
```

한편, 종교별 지지도에 차이가 있는지 살펴보려면, 카이제곱 검정을 `poll.87.tbl`에 적용하면 됨.

```{r}
chisq.test(poll.87.tbl)
```


뒷 마무리
---------

