---
title: "Presidential Election Poll 1987"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

## Data

`table` 구조를 가지므로 우선 `matrix`로 읽어들인다.

```{r}
library(magrittr)
options(digits = 1)
load("./poll87_data.RData")
# poll87_counts <- matrix(c(289, 84, 26, 361, 154, 139, 53, 292, 126, 145, 57, 287, 61, 29, 11, 80), 
#                         nrow = 4, 
#                         ncol = 4)
poll87_counts
class(poll87_counts)
str(poll87_counts)
```

`table` 구조의 변수명을 정한다.

```{r}
dimnames(poll87_counts) <- list(Religion = c("Buddhism", "Protestant", "Catholic", "None"), 
                                 Candidates = c("Roh", "YS", "DJ", "JP", "etc"))
poll87_counts
```

`table` 구조로 강제 변환.

```{r}
counts_tbl <- as.table(poll87_counts)
counts_by_rel_df <- as.data.frame(t(counts_tbl))
str(counts_by_rel_df)
names(counts_by_rel_df)[1] <- "Candidates"
counts_by_rel_df
```

```{r}
counts_by_cand_df <- as.data.frame(counts_tbl)
str(counts_by_cand_df)
names(counts_by_cand_df)[1] <- "Religion"
counts_by_cand_df
```


```{r fig.width=7, fig.height=7}
library(ggplot2)
source("barplot_gg.R")
source("mosaic_gg.R")
```

```{r}
ggplot(data = poll87_tbl, 
       mapping = aes(x = Candidates, y = Counts, fill = Religion)) +
  geom_bar(stat = "identity", 
           position = position_stack()) +
  scale_fill_brewer(type = "div", palette = "Spectral", direction = 1)
```

```{r}
ggplot(data = poll87_tbl, 
       mapping = aes(x = Religion, y = Counts, fill = Candidates)) +
  geom_bar(stat = "identity", position = position_stack()) +
  scale_fill_brewer(type = "div", palette = "Spectral", direction = -1)
```

후보를 색깔로 구분하고 

```{r,  fig.width = 7, fig.height = 7}
barplot_gg_stack(counts_by_rel_df) +
  theme_bw(base_family = "KoPubWorldDotum Medium") +
  labs(title = "1987 대선 갤럽 여론조사", x = "종교", y = "후보 지지인원") +
  scale_x_discrete(labels = c("불교", "개신교", "카톨릭", "무종교")) +
  scale_fill_brewer(name = "후보", labels = c("노태우", "김영삼", "김대중", "김종필", "기타"))
```

```{r,  fig.width = 7, fig.height = 7}
rownames(counts_tbl) <- c("불교", "개신교", "카톨릭", "무종교")
mosaic_gg(t(counts_tbl)) +
  theme_bw(base_family = "KoPubWorldDotum Medium") +
  theme(axis.text.x.top = element_text(family = "KoPubWorldDotum Medium")) +
  labs(title = "1987 대선 갤럽 여론조사", x = "종교", y = "후보 지지도(%)") +
  scale_fill_brewer(type = "qual", name = "후보", labels = c("노태우", "김영삼", "김대중", "김종필", "기타"))
```


종교를 색깔로 구분하면,

```{r,  fig.width = 7, fig.height = 7}
barplot_gg_stack(counts_by_cand_df)
```


